services:
  app-refeicao:
    build: .
    container_name: registro_colaboradores
    privileged: true
    volumes:
      - .:/app
      - /dev:/dev
    ports:
      - "8501:8501"
    restart: unless-stopped